version: '3'

services:

  certbot:
    image: certbot/certbot:v1.4.0
    volumes:
      - ./volumes/letsencrypt:/etc/letsencrypt
    ports: 
      - 80:80
    entrypoint: "certbot certonly --non-interactive --agree-tos -m ${ADMIN_EMAIL} --standalone -d ${BASE_DOMAIN}"

  postgresql:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASS}
      POSTGRES_DB: ${SQL_BASE}

  hmdm:
    image: headwind/hmdm:1.0
    network_mode: host
    depends_on: 
      - certbot
      - postgresql
    volumes:
      - ./volumes/letsencrypt:/etc/letsencrypt
    environment:
      SQL_USER: ${SQL_USER}
      SQL_BASE: ${SQL_BASE}
      SQL_PASS: ${SQL_PASS}
      BASE_DOMAIN: ${BASE_DOMAIN}
      ADMIN_EMAIL: ${ADMIN_EMAIL}

